[package]
name = "remorse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
hound = "3.5.1"
opener = "0.7.2"
rand = "0.8.5"
serde_json = "1.0.131"
